### ISSUE TITLE
XSS security issues

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#338]
https://github.com/Codeinwp/zerif-pro/issues/441

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , @ineagu , I think we can clean the code in customizer for zerif a little bit. For example there are two classes Zerif_Customize_Textarea_Control and Zerif_Customizer_Number_Control .. now wordpress supports those fields in customizer.
There are 4 classes that print a text. We can make only one class and give text as parameter like we do on Parallax One.
I also think that we don't need to check "if ( class_exists( 'WP_Customize_Panel' ) )" ... this was for backward compatibility with 3.9 wp version and it's been a while since then.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu sure, we need to clean the code, just make sure no user is affected :). You can add another issue for this, and maybe assign it yourself next week.

Regarding this "I also think that we don't need to check "if ( class_exists( 'WP_Customize_Panel' ) )" ... this was for backward compatibility with 3.9 wp version and it's been a while since then." I mentioned it once to Ionut but he then said to not remove it. What do you say now @ineagu ?

**Comment by ineagu** [comment]
I will still keep it, I like to don't break people sites :))

On Thu, May 19, 2016 at 1:08 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @cristian-ungureanu <https://github.com/cristian-ungureanu> sure, we need
> to clean the code, just make sure no user is affected :). You can add
> another issue for this, and maybe assign it yourself next week.
>
> Regarding this "I also think that we don't need to check "if (
> class_exists( 'WP_Customize_Panel' ) )" ... this was for backward
> compatibility with 3.9 wp version and it's been a while since then." I
> mentioned it once to Ionut but he then said to not remove it. What do you
> say now @ineagu <https://github.com/ineagu> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/338#issuecomment-220294181>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
@cristian-ungureanu aici foloseai functia zerif_sanitize_text care nu exista. Si ca si idee, poate e mai buna, spunea unul pe wp.org ca pt verificarea checkbox-urilor recomanda wp_validate_boolean
