### ISSUE TITLE
Section titles not translatable

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/zerif-lite#350]
We have changed some section titles from 

’.__($zerif_aboutus_title,’zerif-lite’).'

to:

`’. wp_kses_post( $zerif_aboutus_title ) .'`

Which is causing this issue. We need to add a text domain there. @rodica-andronache

**Comment by rodica-andronache** [comment]
@HardeepAsrani from what I can remember, we removed that because it's wrong. Like it's mentioned here http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/ 

Law the First: Thou shalt not use PHP variables of any kind inside a translation function’s strings.

If the translation is not working, can you please give more details about this? Because I though that having the string in the wpml-config file is enough

**Comment by HardeepAsrani** [comment]
Yes, I think you are right. But we weren't able to translate that part, so can you try if it's appearing in your Polylang?

**Comment by rodica-andronache** [comment]
@HardeepAsrani yes, it's working. You just got to first save the string in Customize, then it will appear in the Polylang strings
