### ISSUE TITLE
Page has unexpected horizontal scroll

### ISSUE THREAD

**Issue by erinknight242** [Codeinwp/zerif-lite#618]
I added this theme, and have done nothing to customize it yet except for changing the background image. When I scroll horizontally on Chrome (Mac), the entire main panel scrolls off the screen, revealing the background image out to the side. This happens if I remove the background image as well. It does not do this in Firefox. If I scroll vertically all the way to the bottom, then it no longer has the horizontal scroll issue. It appears to be the entire "mobilebgfix" div that moves off screen.

Any suggestions?

![scroll](https://user-images.githubusercontent.com/3969554/32422391-a059519e-c265-11e7-8016-96d783a1630d.gif)

**Comment by erinknight242** [comment]
I found the issue; in the console it says: `smoothscroll.js?ver=20120206:412 [Intervention] Registering mousewheel event as passive due to smoothscroll.js usage. The smoothscroll.js library is buggy, no longer necessary and degrades performance. See https://www.chromestatus.com/feature/5749447073988608`

If I disable the smoothscroll.js library, the scrolling works properly.

**Comment by erinknight242** [comment]
Yes; I found that option last night and it works for me. Thanks.

**Comment by rodica-andronache** [comment]
@cosmin-serbanescu could you please investigate this? The problem is that we are enqueueing this script https://github.com/Codeinwp/zerif-lite/blob/production/js/smoothscroll.js which seems to cause problems in Chrome. 
Investigate if there is something we can do maybe in CSS for this to not happen anymore, or an alternative to it, that would work on in all browsers.
