### ISSUE TITLE
Menu item shows double arrows when there is child menus in Mobile

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/zerif-lite#643]
Issue: Menu item shows double arrows when there is child menus in Mobile 

Screenshot: http://prntscr.com/iu5gm0

Ticket: https://secure.helpscout.net/conversation/544701081/157478?folderId=212385

@rodica-andronache

**Comment by rodica-andronache** [comment]
@Vishakha-Patel thanks for reporting this 👍  it doesn't seem to happen just when using a child theme, but with the theme itself too.
@cosmin-serbanescu can you please have a look here? 
This can be also related to the Max Mega Menu plugin, which we are compatible with and use on the demo

**Comment by cosmin-serbanescu** [comment]
fixed them, apparently they were used in mobile as well, tested with Max Menu also and nothing seems to be broken

**Comment by Vishakha-Patel** [comment]
Another relevant issue:

Active Menu item' bottom line is having space on mobile - http://prntscr.com/iurspz

Same Ticket: https://secure.helpscout.net/conversation/544701081/157478/?folderId=212390

@rodica-andronache @cosmin-serbanescu

**Comment by rodica-andronache** [comment]
@cosmin-serbanescu we should remove that active bottom line on the mobile/tablet menu.

The menu still seems to act weird, we need to test **both** with the default wp menu and the Mega Menu.
For example, right now, on demo for both lite and pro, https://demo.themeisle.com/zerif-lite/ https://demo.themeisle.com/zerif-pro/ on mobile/tablet , the first menu item, Features which is linked to the Our Focus section is acting also as a link and a drop-down. I mean, the drop-down arrow and the menu item itself are not separated.
You can't just open the drop-down menu. You are also linked to that page.  You can have a look at shop isle how it handles the menu https://demo.themeisle.com/shop-isle-pro

And, on your fork http://forks.themeisle.com/cosmin-serbanescu/zerif-lite/development/, on tablet, it seems that the drop-down menus are opening on hover, instead of on click like they should.
If you could have a look 💯

**Comment by cosmin-serbanescu** [comment]
@rodica-andronache , removed that line and also re-did the max menu plugin integration according to their docs - apparently when you're using #site-navigation it interferes with their plugin and may cause bugs.
Let me know if everything's all right so I can add it to the pro version as well. 
... and I might have a problem with the fork, I'll speak to Bogdan.
