### ISSUE TITLE
Max Mega Menu compatibility

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#650]
Check how the hover color is working. Can it be changed from the plugin
https://prnt.sc/iygvrm

**Comment by rodica-andronache** [comment]
@cosmin-serbanescu 👍 
- You need to also check the menu when no menu is selected ( when is taking all latest pages ). This is how it looks now https://prnt.sc/j0o0vk and how it looked before https://prnt.sc/j0o0ok
- it would be a good idea to also make the menu compatible with Orbit Fox menu icons functionality ( in this way you can also check OBFX ) https://prnt.sc/j0ooq4 This is the normal menu, but it needs to also look good with mega menu. 
- and for mega menu, I'm not sure, with the default options it looks like this for https://prnt.sc/j0or0x all white, and black on hover. And not vertically aligned. Am I missing something?
- and on forks, I saw that for mega menu, on mobile, the toggle/closing look different than the button in the normal menu https://prnt.sc/j0onqd . Can we have it the same?

**Comment by cosmin-serbanescu** [comment]
@rodica-andronache 
- created a Zerif Lite theme for Max Mega Menu in which I've applied all the styling from the demo + changed that blue color on hover to Zerif's orange hover. Now I also have the option to make that the default theme when activating Zerif Lite or the plugin but I imagine since this is not a new theme and perhaps clients already styled the Max Menu it won't be cool.
- fixed the header extra spacing on the bottom also
- aligned Orbit Fox icons when using/not using Max Mega Menu
- unfortunately for the toggle button that's not much I can do because now we are using their toggle button that's actually dashicon instead of Zerif's extra HTML. I've styled it to be as identical as possible but there are still some slight differences between them.

**Comment by rodica-andronache** [comment]
@cosmin-serbanescu is looking better 👍 
- still what would need to be done is make sure the max mega menu is vertically aligned like before ( when using the default theme ). This is before https://prnt.sc/j3gwln and this is now https://prnt.sc/j3gwh0.
- Plus, on your fork on mobile the menu is looking really bad if you check http://forks.themeisle.com/cosmin-serbanescu/zerif-lite/development/ . Is this because of the fork not being synchronized? (if so, please check with Bogdan, to be sure the code is correct there, so we can see the exact changes in wraith ). I'm asking because I checked on my local with a simple mega menu, and it's important to see what's happening with a more complex one like the one on forks/demo

**Comment by rodica-andronache** [comment]
here there is still that small problem on mobile that we talked about. With the toggle button overlapping the title/logo , with megamenu 👍
