### ISSUE TITLE
Recommend/Make compatible with WPForms Lite instead of PirateForms

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#673]
Make sure theme is compatible with https://wordpress.org/plugins/wpforms-lite/
Recommend WPForms Lite instead of Pirate Forms everywhere in the theme ( about page, customizer frontpage contact section etc )

Plus add this:
if ( ! defined( 'WPFORMS_SHAREASALE_ID' ) ) {
define( 'WPFORMS_SHAREASALE_ID', '848264' );
}

https://github.com/Codeinwp/hestia-pro/issues/1654

**Comment by radu-themeisle** [comment]
-I finished adding the recommendation, the plugin installs / deactivates correct.

-I've already added style for WPForms but the user needs to manually adjust the form to get the layout like pirate forms (manually select 3 column layout, large inputs, hide labels & proper placeholder text).
We cannot create a predefined form, but I was thinking we could make a doc with the necessary steps to style a WPForm like the Pirate Forms one and then add a "zerif" class to the form and the styling that I've done so that it specifically targets the "Pirate Forms like" form.
Right now, it targets WPForm generally so users will need to overwrite the styling.

-I've also added the WPFORMS_SHAREASALE_ID.
